import type { AskAgentPromptId } from "./types";

/** Sample vars for quality review (Copy sample) and vitest fixtures. */
export const ASK_AGENT_PROMPT_FIXTURES: Record<AskAgentPromptId, Record<string, string>> = {
  "organic-page2": {
    query: "coding bootcamp",
    url: "/en/location/berlin-germany",
    position: "11.5",
    impressions: "150",
    window_label: "7d",
    mcp_url: "http://localhost:5000/mcp",
  },
  "organic-low-ctr": {
    query: "ai software engineering",
    url: "/en/blog/example",
    position: "3.2",
    impressions: "2000",
    ctr: "1.2%",
    expected_ctr: "4.0%",
    window_label: "7d",
    mcp_url: "http://localhost:5000/mcp",
  },
  "organic-missing-serp": {
    query: "what is a coding bootcamp",
    url: "/en/blog/example",
    position: "2.1",
    impressions: "800",
    serp_status: "snippet · not owning feature",
    window_label: "7d",
    mcp_url: "http://localhost:5000/mcp",
  },
  "organic-link-gaps": {
    url: "/en/location/berlin-germany",
    position: "8.0",
    impressions: "400",
    inbound: "1",
    window_label: "7d",
    mcp_url: "http://localhost:5000/mcp",
  },
  "page-diagnostics": {
    url: "/en/blog/example",
    content_type: "blog",
    slug: "example",
    locale: "en",
    variant_line: "",
    file_path: "site_x/blog/example/en.yml",
    mcp_url: "http://localhost:5000/mcp",
    error_block: "- META_MISSING [id=abc]: missing description",
    warning_block: "- (none)",
  },
  "draft-feedback": {
    share_url: "https://example.com/en/blog/example?force_variant=draft1",
    content_type: "blog",
    slug: "example",
    locale: "en",
    variant: "draft1",
    mcp_url: "http://localhost:5000/mcp",
  },
  "section-variant-swap": {
    url: "/en/career-programs/full-stack",
    content_type: "programs",
    slug: "full-stack",
    locale: "en",
    page_variant: "live",
    section_index: "3",
    section_heading: "Learn to code with mentors who work in the industry",
    component: "two_column",
    from_version: "v1.0",
    from_variant: "imageRight",
    to_version: "v1.0",
    to_variant: "showcase",
    shared_template_line:
      "- Shared template: this section is used by many pages. Confirm with me before writing.",
    mcp_url: "http://localhost:5000/mcp",
  },
  "redirect-overwrites-content": {
    redirect_url: "/en/career-programs/cybersecurity",
    source_file: "site_4geeks-com/programs/other/en.yml",
    code: "REDIRECT_OVERWRITES_CONTENT",
    description: "This redirect is hiding an existing page. Remove it so visitors can see the page.",
    mcp_url: "http://localhost:5000/mcp",
  },
  "resolved-issue-context": {
    issue_id: "iss-1",
    code: "ORPHAN_PAGE",
    severity: "warning",
    validator: "seo-cluster",
    url: "/es/blog/example",
    content_type: "blog",
    slug: "example",
    locale: "es",
    variant_line: "",
    file_path: "site_x/blog/example/es.yml",
    mcp_url: "http://localhost:5000/mcp",
    message: 'blog page "example" (es) has no seo block — it belongs to no cluster',
    resolved_at: "2026-09-02T20:00:00.000Z",
    resolved_by: "staff@example.com",
    reopened_line: "",
  },
  "proposal-bad-outcome": {
    proposal_id: "prop-abc123",
    title: "Tighten meta description on /en/blog/example",
    kind: "edits",
    status: "finished",
    close_reason: "applied",
    mcp_url: "http://localhost:5000/mcp",
    what_went_wrong:
      "Applied a description that dropped the primary keyword; CTR fell the following week.",
    expected: "Reviewer should have kept the keyword in the first 120 characters or rejected.",
    reviewed_by: "steward@example.com on 2026-09-20",
    decision_block:
      "- decided: apply by reviewer@example.com (staff, ui)\n- damage class: live_copy · undo cost: low\n- think items: Keyword retention; Recent writes\n- warnings: (none)",
  },
  "polish-ask-agent-prompt": {
    target_id: "organic-page2",
    target_title: "Page 2 opportunity",
    target_path: "shared/ask-agent-prompts/organic-page2.md",
    target_used_when: "Staff clicks Ask Agent on Page 2 rows.",
    target_intention: "Move one query×URL toward page 1.",
    target_success: "Scoped edits or propose_change; short summary.",
    target_failure_modes: "  - Rewrites unrelated pages\n  - Generic SEO with no query focus",
    target_raw:
      "---\nid: organic-page2\nversion: 1\ntitle: Page 2 opportunity\n---\n\nGoal: Move this page toward page 1.\n",
    max_chars: "1200",
  },
};
